sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - sudo apt-get install g++-6 libboost-all-dev valgrind clang-3.8
    - sudo pip install codecov
    - sudo pip install gcovr

matrix:
    include:
        - env:
            - COMPILER=g++-6
            - JOB=coverage
        - env: 
            - COMPILER=clang++-3.8
            - JOB=coverage
        - env:
            - COMPILER=g++-6
              JOB=valgrind

language: cpp
script:
    - ./ci.sh $JOB

after_success:
    - codecov

