sudo: required

language: cpp

matrix:
    include:
        - env:
            - COMPILER=g++
            - JOB=coverage
          services:
            - docker
        - env:
            - COMPILER=clang++-3.8
              JOB=coverage
          services:
            - docker
        - env:
            - COMPILER=g++
              JOB=valgrind
          services:
            - docker

language: cpp
script:
    - ./ci.sh

