sudo: required
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - valgrind

compiler: g++-6

cache:
    - ccache
    - packages

language: cpp
script:
    - mkdir -p build && cd build
    - CXX=g++-6 CC=gcc-6 cmake ..
    - make
    - ./test/tests
