sudo: required

language: cpp

before_install:
    - docker pull mrokkk/devel

matrix:
    include:
        - env:
            - COMPILER=g++
            - JOB=coverage
            - IMAGE=mrokkk/devel
            - CODECOV=1
          services:
            - docker
        - env:
            - COMPILER=clang++
            - JOB=coverage
            - IMAGE=mrokkk/devel
          services:
            - docker
        - env:
            - COMPILER=g++
            - JOB=valgrind
            - IMAGE=mrokkk/devel
          services:
            - docker

language: cpp
script:
    - ./ci.sh

